name: flutter_tilt_book
description: Flutter Tilt.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.0
  flutter_tilt: ^1.0.3
  syntax_highlight: ^0.2.0
  remixicon_updated: ^1.0.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/parallax_image/