name: 'Deploy GitHub Pages'
run-name: 'Deploy GitHub Pages'

# Disable permissions for all of the available permissions
permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-node@0355742c943ddb13ca8a6b700f824231caa91e75
        with:
          node-version: 24
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: 'stable'
          flutter-version-file: flutter_tilt_example/pubspec.yaml
      - name: Prepare dependencies (flutter_tilt_example)
        run: |
          cd flutter_tilt_example
          flutter --version
          flutter pub get
      - name: Check Dart code formatting
        run: |
          dart format . -o none --set-exit-if-changed
      - name: Analyze Dart code
        run: |
          flutter analyze .
      - name: Prepare dependencies (flutter_tilt_book)
        run: |
          cd flutter_tilt_book
          node --version
          npm --version
          npm i
      - name: Check code formatting
        run: |
          cd flutter_tilt_book
          npm run lint
          npm run format:check

  deploy:
    needs: [code-analysis]
    if: github.repository == 'AmosHuKe/flutter_tilt_book'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-node@0355742c943ddb13ca8a6b700f824231caa91e75
        with:
          node-version: 24
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: 'stable'
          flutter-version-file: flutter_tilt_example/pubspec.yaml
      - name: Prepare dependencies
        run: |
          cd flutter_tilt_example
          flutter --version
          flutter pub get
          cd ../flutter_tilt_book
          node --version
          npm --version
          npm i
      - name: Build flutter_tilt_example Web (wasm)
        run: |
          cd flutter_tilt_book
          bash tools/build-flutter-tilt-example.sh
        shell: bash
      - name: Build flutter_tilt_bool Web
        run: |
          cd flutter_tilt_book
          npm run generate-search-data
          npm run build
        shell: bash
        env:
          NEXT_PUBLIC_FLUTTER_TILT_EXAMPLE_URL: /flutter_tilt_book
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          branch: 'pages-book'
          folder: 'flutter_tilt_book/out'
